### ISSUE TITLE
code problem

### ISSUE THREAD

**Issue by DarrenQu** [zllxot/CORE#2]
Thank you for sharing the source code, but can not find the code of sub_modules.att_bev_backbone_core
![image](https://github.com/zllxot/CORE/assets/78702377/165a3a7f-da2d-4f50-87e7-a6d21e807e5c)

**Comment by Sun1boy** [comment]
I have the same question. Did you solve it?

**Comment by zllxot** [comment]
Thank you for your attention and inquiry. I have updated the code.

**Comment by Sun1boy** [comment]
Hello, thanks for your help.
But modules opencood.models.sub_modules.att_bev_backbone_core and opencood.models.sub_modules.att_bev_backbone_v2 are still missing in opencood\models\point_pillar_core.py and opencood\models\point_pillar_core_v2.py
![image](https://github.com/zllxot/CORE/assets/119661643/758f2ec3-ceac-4ae8-86a8-e1c84e2af1bf)

![image](https://github.com/zllxot/CORE/assets/119661643/b2bb4677-8004-40d0-92a7-13531da5dc3d)
